#spring.datasource.url=jdbc:h2:mem:bank
#spring.h2.console.enabled=true
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

jwt.secret="aB9xK2mP7qW4tY8uZ1nR5vC3sD6fGhJ0LpQeRtYuIoPaSdFgHjKlMnBvCxZ12345"


# --- Configuration Spring AI & OpenAI ---
# Nous utilisons la variable d'environnement pour la clé afin de la garder secrète
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o

# --- Configuration Telegram Bot ---
# Le token fourni par BotFather sur Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=Ebanking_Sohail_bot
